debug_mode_enable: false
max_merge_dist: 0.02
stat_removal:
  enable: false
  kmeans: 500
  stddev: 2.0
downsample:
  enable: true
  voxel_leafsize: 0.005
sequencing:
  kdtree_epsilon: 0.00001
  search_radius: 0.02
normal_est:
  search_radius: 0.01
  kdtree_epsilon: 0.00001
  viewpoint_xyz: [0.0, 0.0, 100.0]